<div class="container-fluid h-100">
	<div class="row">
    
    <div class="col-md-6 p-0">
		<div class="img-bg"></div>
	</div>

    <div class="col-md-6 pt-4 pl-5 pr-5 my-5">
		<form method="post" action="/autenticate">
			<div class="row">
				<div class="col">
					<input type="email" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="password" class="form-control" placeholder="Password">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>

			<?php if($this->view->login == 'error') { ?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*E-mail e/ou password inválido(s)</span>
					</div>
				</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<h1 class="title">Bem vindo</h1>

				<h2 class="mt-5 subtitle">Registe-se já!</h2>
				<a href="/signup" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>