<!DOCTYPE html>
<html lang="pt">
<head>
	<title>Microframework</title>
	<meta charset="utf-8">
	<meta name="description" content="lab">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="keywords" content="microframework">
	<meta name="author" content="Hernâni_Medeiros">

	<!-- CDN libs -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"/>

	<!-- Custom libs -->
	<link rel="stylesheet" type="text/css" href="..//css/global.css"/>
	<style></style>
</head>

<body>
	<?= $this->content() ?>
	<!-- Footer -->
	<footer class="container-fluid bg-dark text-center fixed-bottom">
		<a class="nav-link" href="./">
			<small style="color:whitesmoke">
				<span>MVC Microframework made with&nbsp</span>
				<i class="fas fa-heart" style="color:#E1674D"></i> &nbspin&nbsp
				<i class="fab fa-php" style="font-size:1.5rem"></i>	&nbspby Hernâni Medeiros
			</small>
		</a>
	</footer>

	<!-- CDN libs -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://kit.fontawesome.com/34ea097e0f.js"></script>
	
</body>

</html>